// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADUh2OxGjZIL7acW6eeGDA7b8OM5mn5zw',
    appId: '1:301900627137:web:a5148a7a2d6c2945bae840',
    messagingSenderId: '301900627137',
    projectId: 'tami-c22b2',
    authDomain: 'tami-c22b2.firebaseapp.com',
    databaseURL: 'https://tami-c22b2-default-rtdb.firebaseio.com',
    storageBucket: 'tami-c22b2.appspot.com',
    measurementId: 'G-8Q3ZNJ83X2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG_8VmG2DxbhvbEu1VYCcigvZOgUTDhHQ',
    appId: '1:301900627137:android:dba4e5b6bed4481cbae840',
    messagingSenderId: '301900627137',
    projectId: 'tami-c22b2',
    databaseURL: 'https://tami-c22b2-default-rtdb.firebaseio.com',
    storageBucket: 'tami-c22b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnsNFXEKsCsbdxLFrpYSPJUdryiy-VHDc',
    appId: '1:301900627137:ios:268dd7ae97f3e1fabae840',
    messagingSenderId: '301900627137',
    projectId: 'tami-c22b2',
    databaseURL: 'https://tami-c22b2-default-rtdb.firebaseio.com',
    storageBucket: 'tami-c22b2.appspot.com',
    iosClientId: '301900627137-isg4k38tpfmuvr3nvn0v957b38tglv9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.tami',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnsNFXEKsCsbdxLFrpYSPJUdryiy-VHDc',
    appId: '1:301900627137:ios:268dd7ae97f3e1fabae840',
    messagingSenderId: '301900627137',
    projectId: 'tami-c22b2',
    databaseURL: 'https://tami-c22b2-default-rtdb.firebaseio.com',
    storageBucket: 'tami-c22b2.appspot.com',
    iosClientId: '301900627137-isg4k38tpfmuvr3nvn0v957b38tglv9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.tami',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADUh2OxGjZIL7acW6eeGDA7b8OM5mn5zw',
    appId: '1:301900627137:web:9f2df9fdf6e81f28bae840',
    messagingSenderId: '301900627137',
    projectId: 'tami-c22b2',
    authDomain: 'tami-c22b2.firebaseapp.com',
    databaseURL: 'https://tami-c22b2-default-rtdb.firebaseio.com',
    storageBucket: 'tami-c22b2.appspot.com',
    measurementId: 'G-T39M8CLHWJ',
  );
}
